#!/usr/bin/env python3

# Python script to run and analyse MMS test

import sys

import numpy as np
from boutdata.collect import collect
from boututils.run_wrapper import launch_safe, shell
from numpy import abs

gridpath = "../../../grids/slab_with_BC/"


def gridname(ny):
    return gridpath + "MMS_straight_slab_8_128_4_True.fci.grid.nc"


nout = 10
timestep = 1e4 / nout

nproc = 1


args = f"nout={nout} timestep={timestep}"

print("Running with " + args)

# Delete old data
shell("rm data/BOUT.dmp.*.nc")

# Command to run
cmd = "../../../hermes-3 " + args
# Launch using MPI
_, out = launch_safe(cmd, nproc=nproc, pipe=True)


success = True


Pi = np.mean(
    collect("Ph+", tind=[nout, nout], path="data", info=False)[-1], axis=(0, 2)
)
Pe = np.mean(collect("Pe", tind=[nout, nout], path="data", info=False)[-1], axis=(0, 2))
Ni = np.mean(
    collect("Nh+", tind=[nout, nout], path="data", info=False)[-1], axis=(0, 2)
)

tol = 1e-5

for var, lab in zip([Pe, Pi, Ni], ["Pe", "Pi", "Ni"]):
    if abs(var[0] - var[-1]) > tol:
        print(f"Asymmetry in {lab}!", var[0], var[-1])
        success = False

    print(f"{lab}: ", var[0])


Nival = 0.25647799178771336
if abs(Ni[0] - Nival) > tol:
    print("Density mismatch. ", abs(Ni[0] - Nival))
    success = False

Pival = 0.17425070863314052
if abs(Pi[0] - Pival) > tol:
    print("Pi mismatch. ", abs(Pi[0] - Pival))
    success = False

Peval = 0.25205122346033126
if abs(Pe[0] - Peval) > tol:
    print("Pe mismatch. ", abs(Pe[0] - Peval))
    success = False


if success:
    print(" => Test passed")
    sys.exit(0)
else:
    print(" => Test failed")
    sys.exit(1)
