#!/usr/bin/env python3

# A simple 1D test that starts several species below their respective density thresholds for low-n source activation.
# In postprocessing, check that the sources activated at all of the grid locations and times expected from the design.
#
# Note that the correctness of source values (as opposed to just source activation state) is checked by the unit tests.

from __future__ import division
from __future__ import print_function

from boututils.run_wrapper import launch_safe

import numpy as np
import pathlib
import xhermes

this_dir = pathlib.Path(__file__).parent
data_dir = this_dir / "data"
hermes_exec = this_dir.parent.parent.parent / "hermes-3"
data_path = data_dir / "BOUT.dmp.0.nc"

# If the test fails, set this to True to get more detailed output
# (tends to be slow, so disabled by default)
debug = False

# molecules aren't included in this test, so skip association source checks
skip_checks_for_types = ["association"]


# =============================================================================
# Helper functions
def compute_trigger_mask(
    ds,
    target_species,
    gate_species="",
    boost_species="",
    require_boost_sp_deficit=False,
):
    """Find data points (over whole grid and at all times) where the trigger conditions for a source are expected to be satisfied."""

    floor_to_th_fac = ds.options["low_n_sources"]["low_n_floor_fac"]
    ntarget = get_density(ds, target_species, "target")
    target_th = (
        ds.options[target_species].as_dict().get("density_floor", 1e-7)
        * floor_to_th_fac
    )
    # Assemble mask identifying data points where the source should trigger
    should_trigger = ntarget < target_th

    # Apply gate condition if one was specified
    if gate_species:
        ngate = get_density(ds, gate_species, "gate")
        ngate_th = (
            ds.options[gate_species].as_dict().get("density_floor", 1e-7)
            * floor_to_th_fac
        )
        should_trigger &= ngate > ngate_th

    # Apply boost condition if specified
    if boost_species:
        nboost = get_density(ds, boost_species, "boost")
        boost_th = (
            ds.options[boost_species].as_dict().get("density_floor", 1e-7)
            * floor_to_th_fac
        )
        # Boost is ignored for now unless require_boost_sp_deficit=true
        # Could check the exact value of the source in future?
        if require_boost_sp_deficit:
            should_trigger &= nboost < boost_th

    return should_trigger.compute()


def end_test(success, msg="", err_code=1):
    if success:
        print(" => Test passed")
        exit(0)
    else:
        print(" => Test failed")
        if msg:
            print(msg)
        exit(err_code)


def fail_on_missing_data():
    if not data_path.is_file():
        fail_test(err_code=2, msg=f"No data at {data_path}")


def fail_on_missing_exec():
    if not hermes_exec.is_file():
        fail_test(err_code=3, msg=f"No executable found at {hermes_exec}")


def fail_test(**kws):
    end_test(False, **kws)


def get_density(ds, species, sp_type):
    """Get the density of a species from the dataset, checking that the species exists first"""
    if species not in ds.options:
        print(f"ERROR: '{sp_type}' species [{species}] not found in output file")
        print("WOULD FAIL TEST")
    density_fld = f"N{species}"
    return ds[density_fld]


# =============================================================================
# Test body

success = True

# Make sure the executable is where it should be
fail_on_missing_exec()

# Remove existing output
data_path.unlink(missing_ok=True)

# Use boututils wrapper to run exec
s, run_stdout = launch_safe(f"{hermes_exec} -d {data_dir}", nproc=1, pipe=True)

# Save output to log file
with open("run.log", "w") as f:
    f.write(run_stdout)

# Check that the run produced output
fail_on_missing_data()

# Read output
ds = xhermes.open(data_dir, unnormalise=False)

# Make sure a valid low-n strategy was used
valid_strategies = ["standard"]
strategy_used = ds.options["low_n_sources"]["strategy"]
if strategy_used not in valid_strategies:
    fail_test(
        err_code=4,
        msg=f"This test is valid only for low-n source strategies [{', '.join(valid_strategies)}], but '{strategy_used}' was used.",
    )

# Exclude guards
ds = ds.isel(pos=slice(2, -2))

# For each element/isotope, compute a mask that identifies data points where a low-n source should trigger,
# then check that the source diagnostic is +ve at those points and zero elsewhere.
for atom_sp in ["d", "t"]:
    ion_sp = f"{atom_sp}+"
    mol_sp = f"{atom_sp}2"
    for src_type in ["association", "recombination", "ionization", "external_src"]:
        # Set trigger species, thresholds based on source type
        if src_type in skip_checks_for_types:
            continue
        if src_type == "association":
            target_sp = mol_sp
        elif src_type == "recombination":
            target_sp = atom_sp
        else:
            target_sp = ion_sp
        gate_sp = atom_sp if src_type == "ionization" else ""
        boost_sp = atom_sp if src_type == "external_src" else ""
        require_boost_sp_deficit = src_type == "external_src"

        # Identify data points where the source should trigger
        trigger_mask = compute_trigger_mask(
            ds,
            target_sp,
            gate_sp,
            boost_sp,
            require_boost_sp_deficit=require_boost_sp_deficit,
        )

        # Get the source values
        source_name = f"S{target_sp}_low-n_{src_type}"
        source = ds[source_name].values

        # Check that the source is +ve when the trigger should activate, zero otherwise
        source_state_correct = np.all(np.where(trigger_mask, source > 0, source == 0))
        success &= source_state_correct

        # Extra debugging info (if enabled) when the source state wasn't as expected.
        if debug and not source_state_correct:
            print(f"DEBUG: {source_name} source didn't turn on/off where expected.")
            print(
                "DEBUG: Checking each time output separately (will exit on first error)"
            )
            for tidx, trigger_mask_t in enumerate(trigger_mask):
                source_t = source[tidx]
                if not np.all(source_t[trigger_mask_t] > 0):
                    print(
                        f"  ERROR: t = {tidx}: source {source_name} not positive at all expected points"
                    )
                    print(
                        f"  (source size is {source_t.size}, mask size is {trigger_mask_t.size})"
                    )
                    break
                if not np.all(source_t[~trigger_mask_t] == 0):
                    print(
                        f"  ERROR: t = {tidx}: source {source_name} not zero at all expected points"
                    )
                    print(
                        f"  (source size is {source_t.size}, mask size is {trigger_mask_t.size})"
                    )
                    break
                print(f"  DEBUG: t = {tidx} state correct")
end_test(success)
