spack:

  view: /opt/views/view

  specs:
  - python@3.12
  - py-cython
  - py-numpy
  - py-pip
  - py-jinja2
  - cmake
  - netcdf-cxx4
  - openmpi
  - openblas
  - hypre +mpi
  - sundials +petsc+hypre+mpi~examples~examples-install
  - petsc +double+fftw+hdf5+hypre+mpi
  - slepc

  concretizer:
    unify: true