#!/usr/bin/env python3

# Python script to run cases and check particle conservation

import sys
from pathlib import Path

import numpy as np
from boutdata.collect import collect
from boututils.run_wrapper import launch_safe, shell

tolerance = 1e-12

# Settings to use
nylist = [16]
nprocs = [1, 2]
settings = [
    "'hermes:components=h+' 'h+:temperature=1.0'",
    "'hermes:components=h+' 'h+:temperature=1.0+H(y-pi)'",
    "'hermes:components=h+, sound_speed' 'h+:temperature=1.0'",
    "'hermes:components=h+, sound_speed' 'h+:temperature=1.0+H(y-pi)'",
]

success = True

for nproc in nprocs:
    for ny in nylist:
        for ind, setting in enumerate(settings):
            args = f"mesh:ny={ny} {setting}"

            print(f"Processors {nproc} args " + args)

            # Delete old data
            shell("rm data/BOUT.dmp.*.nc")

            # Command to run
            cmd = "../../../hermes-3 " + args
            # Launch using MPI
            _, out = launch_safe(cmd, nproc=nproc, pipe=True)
            Path(f"run.log.{nproc}.{ny}.{ind}").write_text(out)

            # Collect data
            total_n = np.sum(collect("Nh+", path="data", info=False).squeeze(), axis=-1)
            err = abs(total_n[-1] - total_n[0])
            print(f"    Error={err}", end="")
            if err < tolerance:
                print(" -> Passed")
            else:
                print(" -> Failed")
                success = False

if success:
    print(" => Test passed")
    sys.exit(0)
else:
    print(" => Test failed")
    sys.exit(1)
