name: Build hermes-3-builder and hermes-3 Docker images

# Configures this workflow to run when a release is released, or when manually triggered.
on:
  workflow_dispatch:  # Allows manual triggering
  release:
    types: [released]
  schedule:
    # Run monthly, at midnight on the first day of the month
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io
  BUILDER_IMAGE_NAME: boutproject/hermes-3-builder
  FINAL_IMAGE_NAME: boutproject/hermes-3
  BUILDER_DOCKERFILE: docker/hermes-3-builder.dockerfile
  FINAL_DOCKERFILE: docker/hermes-3.dockerfile

jobs:

  build-builder-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BUILDER_IMAGE_NAME }}
          tags: |
            # set "latest" tag
            type=raw,value=latest
            # short sha tag
            type=sha
            # tag with semantic version
            type=semver,pattern={{version}}
            # tag with date
            type=schedule,pattern={{date 'YYYYMMDD'}}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.BUILDER_DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  build-final-image:

    needs: build-builder-image
    runs-on: ubuntu-latest
    if: needs.build-builder-image.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FINAL_IMAGE_NAME }}
          tags: |
            # set "latest" tag
            type=raw,value=latest
            # short sha tag
            type=sha
            # tag with semantic version
            type=semver,pattern={{version}}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.FINAL_DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  