---
name: Tests
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  cmake_tests:
    name: ${{ matrix.configure_options }}, ${{ matrix.test_type }} tests
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 1
      PYTHONPATH: ${{ github.workspace }}/tools/pylib
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np
      LD_LIBRARY_PATH: /home/runner/local/lib:$LD_LIBRARY_PATH
      BOUT_CONFIGURE_OPTIONS: ${{ matrix.configure_options }}
      BUILD_TYPE: RelWithDebInfo
      TEST_TYPE: ${{ matrix.test_type }}
    strategy:
      fail-fast: false
      matrix:
        test_type: ['unit', 'integration']
        configure_options: ["-DBOUT_ENABLE_METRIC_3D=ON -DBOUT_DOWNLOAD_SUNDIALS=ON", ""]


    steps:
      - name: Job information
        run: |
          echo Build: ${{ matrix.test_type }}
          echo Configure options: ${{ matrix.configure_options }}
          echo Tests to run: ${{ matrix.test_type }}

      - name: Install dependencies
        run: sudo apt update &&
             sudo apt install -y
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdf-c++4-dev
                 netcdf-bin
                 python3
                 python3-pip
                 python3-pytest
                 python3-numpy
                 python3-scipy
                 openmpi-bin
                 libopenmpi-dev
                 liblapack-dev
                 libparpack2-dev
                 petsc-dev

      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
                           -DHERMES_ERROR_ON_WARNINGS=ON \
                           -DHERMES_COVERAGE=ON \
                           $BOUT_CONFIGURE_OPTIONS
          cmake --build build -j4

      - name: Install pip packages
        run: |
          ./.pip_install_for_tests.sh 'netcdf4~=1.5' boutdata boututils git+https://github.com/boutproject/xhermes git+https://github.com/boutproject/zoidberg@better-metric
          # Add the pip install location to the runner's PATH
          echo ~/.local/bin >> $GITHUB_PATH
      - name: Run tests
        run: cd build &&
             ctest --output-on-failure --timeout 300 -L $TEST_TYPE
      - name: Upload test coverage data
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.test_type }}
